name: CI/CD Pipeline

on:
  pull_request_target:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add other steps for building and pushing Docker images, etc.
