name: EC2 Command Pull

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOC_USERNAME }}
          password: ${{ secrets.DOC_PASS }}

      # Add other steps for SSH setup and pulling Docker images on EC2.
